services:
  pililo-mock-server:
    image: ghcr.io/gveraa/pililo-trader-mock-server:latest
    container_name: pililo_mock_server
    ports:
      - "8080:8080"
    volumes:
      - ./mocks:/app/mocks
    environment:
      - MOCKS_DIR=mocks
      - ENABLE_FILE_LOGGING=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"